import type { DiscordSetupTemplate } from "./types";

export const contentClipsHubDiscordTemplate: DiscordSetupTemplate = {
  schemaVersion: 1,
  id: "content-clips-hub",
  name: "Content And Clips Hub",
  description:
    "A media-forward creator layout for clips, highlights, setup sharing, content ideas, live notices, and community feedback.",
  recommendedFor:
    "Creators who want Discord to collect moments, ideas, media, and viewer suggestions around stream content.",
  roles: [
    {
      id: "stream-alerts",
      name: "Stream Alerts",
      color: 0x39d9ff,
      mentionable: true,
      hoist: false,
    },
  ],
  channels: [
    { id: "category-start-here", name: "START HERE", kind: "category" },
    {
      id: "welcome",
      name: "welcome",
      kind: "text",
      parentId: "category-start-here",
      topic: "New member landing page and server orientation.",
    },
    {
      id: "rules",
      name: "rules",
      kind: "text",
      parentId: "category-start-here",
      topic: "Server rules and community expectations.",
    },
    {
      id: "announcements",
      name: "announcements",
      kind: "text",
      parentId: "category-start-here",
      topic: "General creator notices and updates.",
    },
    { id: "category-stream", name: "STREAM", kind: "category" },
    {
      id: "live-now",
      name: "live-now",
      kind: "text",
      parentId: "category-stream",
      topic: "Stream start, late, cancelled, and schedule notices.",
    },
    {
      id: "schedule",
      name: "schedule",
      kind: "text",
      parentId: "category-stream",
      topic: "Upcoming stream schedule and changes.",
    },
    {
      id: "suggestions",
      name: "suggestions",
      kind: "text",
      parentId: "category-stream",
      topic: "Community suggestions for streams, games, and segments.",
    },
    { id: "category-content", name: "CONTENT", kind: "category" },
    {
      id: "clips-and-highlights",
      name: "clips-and-highlights",
      kind: "text",
      parentId: "category-content",
      topic: "Clips, highlights, and stream moments.",
    },
    {
      id: "screenshots",
      name: "screenshots",
      kind: "text",
      parentId: "category-content",
      topic: "Screenshots and visual moments from streams and games.",
    },
    {
      id: "content-ideas",
      name: "content-ideas",
      kind: "text",
      parentId: "category-content",
      topic: "Stream, video, clip, and community event ideas.",
    },
    {
      id: "setup-share",
      name: "setup-share",
      kind: "text",
      parentId: "category-content",
      topic: "Streaming setups, gear, software, and workflow notes.",
    },
    {
      id: "fan-art",
      name: "fan-art",
      kind: "text",
      parentId: "category-content",
      topic: "Community art, edits, memes, and creative posts.",
    },
    { id: "category-community", name: "COMMUNITY", kind: "category" },
    {
      id: "general",
      name: "general",
      kind: "text",
      parentId: "category-community",
      topic: "Default community chat.",
    },
    {
      id: "creator-chat",
      name: "creator-chat",
      kind: "text",
      parentId: "category-community",
      topic: "Creator process, goals, and content discussion.",
    },
    {
      id: "off-topic",
      name: "off-topic",
      kind: "text",
      parentId: "category-community",
      topic: "Casual community conversation.",
    },
    { id: "category-voice", name: "VOICE", kind: "category" },
    {
      id: "voice-lobby",
      name: "Lobby",
      kind: "voice",
      parentId: "category-voice",
    },
    {
      id: "voice-editing-room",
      name: "Editing Room",
      kind: "voice",
      parentId: "category-voice",
      userLimit: 6,
    },
    {
      id: "voice-watch-party",
      name: "Watch Party",
      kind: "voice",
      parentId: "category-voice",
      userLimit: 12,
    },
    {
      id: "voice-afk",
      name: "AFK",
      kind: "voice",
      parentId: "category-voice",
    },
    { id: "category-staff", name: "STAFF", kind: "category" },
    {
      id: "staff-chat",
      name: "staff-chat",
      kind: "text",
      parentId: "category-staff",
      topic:
        "Private staff coordination for stream-day notes, moderation handoffs, event prep, and Console action review.",
    },
    {
      id: "mod-log",
      name: "mod-log",
      kind: "text",
      parentId: "category-staff",
      topic: "Moderation notes and VaexCore community operations logs.",
    },
    {
      id: "content-planning",
      name: "content-planning",
      kind: "text",
      parentId: "category-staff",
      topic: "Private content planning for staff.",
    },
  ],
  recommended: {
    streamAnnouncementChannelId: "live-now",
    generalAnnouncementChannelId: "announcements",
    suggestionChannelId: "suggestions",
    streamAlertsRoleId: "stream-alerts",
  },
};
