import type { DiscordSetupTemplate } from "./types";

export const eventsGameNightsDiscordTemplate: DiscordSetupTemplate = {
  schemaVersion: 1,
  id: "events-game-nights",
  name: "Events And Game Nights",
  description:
    "A community event layout with schedules, signups, party finding, game rooms, stream notices, and staff event planning.",
  recommendedFor:
    "Creators who run recurring game nights, community events, tournaments, or party queues.",
  roles: [
    {
      id: "stream-alerts",
      name: "Stream Alerts",
      color: 0x39d9ff,
      mentionable: true,
      hoist: false,
    },
  ],
  channels: [
    { id: "category-start-here", name: "START HERE", kind: "category" },
    {
      id: "welcome",
      name: "welcome",
      kind: "text",
      parentId: "category-start-here",
      topic: "New member landing page and server orientation.",
    },
    {
      id: "rules",
      name: "rules",
      kind: "text",
      parentId: "category-start-here",
      topic: "Server rules and community expectations.",
    },
    {
      id: "announcements",
      name: "announcements",
      kind: "text",
      parentId: "category-start-here",
      topic: "General creator notices and updates.",
    },
    { id: "category-events", name: "EVENTS", kind: "category" },
    {
      id: "live-now",
      name: "live-now",
      kind: "text",
      parentId: "category-events",
      topic: "Stream start, late, cancelled, and schedule notices.",
    },
    {
      id: "event-schedule",
      name: "event-schedule",
      kind: "text",
      parentId: "category-events",
      topic: "Upcoming community events and game nights.",
    },
    {
      id: "signups",
      name: "signups",
      kind: "text",
      parentId: "category-events",
      topic: "Event signups, waitlists, and participation notes.",
    },
    {
      id: "lfg",
      name: "lfg",
      kind: "text",
      parentId: "category-events",
      topic: "Looking-for-group and party coordination.",
    },
    {
      id: "suggestions",
      name: "suggestions",
      kind: "text",
      parentId: "category-events",
      topic: "Community suggestions for events, games, and stream segments.",
    },
    { id: "category-games", name: "GAMES", kind: "category" },
    {
      id: "general",
      name: "general",
      kind: "text",
      parentId: "category-games",
      topic: "Default community chat.",
    },
    {
      id: "game-chat",
      name: "game-chat",
      kind: "text",
      parentId: "category-games",
      topic: "Game-specific chat, queue talk, and party coordination.",
    },
    {
      id: "party-finder",
      name: "party-finder",
      kind: "text",
      parentId: "category-games",
      topic: "Find players for co-op, queues, and community lobbies.",
    },
    {
      id: "clips-and-highlights",
      name: "clips-and-highlights",
      kind: "text",
      parentId: "category-games",
      topic: "Clips, highlights, and event moments.",
    },
    { id: "category-voice", name: "VOICE", kind: "category" },
    {
      id: "voice-lobby",
      name: "Lobby",
      kind: "voice",
      parentId: "category-voice",
    },
    {
      id: "voice-game-room-one",
      name: "Game Room 1",
      kind: "voice",
      parentId: "category-voice",
      userLimit: 10,
    },
    {
      id: "voice-game-room-two",
      name: "Game Room 2",
      kind: "voice",
      parentId: "category-voice",
      userLimit: 10,
    },
    {
      id: "voice-event-room",
      name: "Event Room",
      kind: "voice",
      parentId: "category-voice",
      userLimit: 20,
    },
    {
      id: "voice-afk",
      name: "AFK",
      kind: "voice",
      parentId: "category-voice",
    },
    { id: "category-staff", name: "STAFF", kind: "category" },
    {
      id: "staff-chat",
      name: "staff-chat",
      kind: "text",
      parentId: "category-staff",
      topic:
        "Private staff coordination for stream-day notes, moderation handoffs, event prep, and Console action review.",
    },
    {
      id: "mod-log",
      name: "mod-log",
      kind: "text",
      parentId: "category-staff",
      topic: "Moderation notes and VaexCore community operations logs.",
    },
    {
      id: "event-planning",
      name: "event-planning",
      kind: "text",
      parentId: "category-staff",
      topic: "Private event planning and run-of-show notes.",
    },
  ],
  recommended: {
    streamAnnouncementChannelId: "live-now",
    generalAnnouncementChannelId: "announcements",
    suggestionChannelId: "suggestions",
    streamAlertsRoleId: "stream-alerts",
  },
};
