import type { DiscordSetupTemplate } from "./types";

export const streamerCommunityDiscordTemplate: DiscordSetupTemplate = {
  schemaVersion: 1,
  id: "streamer-community-baseline",
  name: "Streamer Community Baseline",
  description:
    "A lean streamer Discord layout with start-here, stream, community, voice, and staff sections.",
  recommendedFor:
    "Small-to-mid streamer communities that need clear live notices, clips, suggestions, general chat, voice, and private staff coordination without a sprawling channel list.",
  roles: [
    {
      id: "stream-alerts",
      name: "Stream Alerts",
      color: 0x39d9ff,
      mentionable: true,
      hoist: false,
    },
  ],
  channels: [
    { id: "category-start-here", name: "START HERE", kind: "category" },
    {
      id: "welcome",
      name: "welcome",
      kind: "text",
      parentId: "category-start-here",
      topic: "New member landing page and server orientation.",
    },
    {
      id: "rules",
      name: "rules",
      kind: "text",
      parentId: "category-start-here",
      topic: "Server rules and community expectations.",
    },
    {
      id: "announcements",
      name: "announcements",
      kind: "text",
      parentId: "category-start-here",
      topic: "General community updates and creator notices.",
    },
    { id: "category-stream", name: "STREAM", kind: "category" },
    {
      id: "live-now",
      name: "live-now",
      kind: "text",
      parentId: "category-stream",
      topic: "Stream start, late, cancelled, and schedule notices.",
    },
    {
      id: "schedule",
      name: "schedule",
      kind: "text",
      parentId: "category-stream",
      topic: "Upcoming stream schedule and changes.",
    },
    {
      id: "clips-and-highlights",
      name: "clips-and-highlights",
      kind: "text",
      parentId: "category-stream",
      topic: "Clips, highlights, and stream moments.",
    },
    {
      id: "suggestions",
      name: "suggestions",
      kind: "text",
      parentId: "category-stream",
      topic: "Community suggestions for streams, games, and segments.",
    },
    { id: "category-community", name: "COMMUNITY", kind: "category" },
    {
      id: "general",
      name: "general",
      kind: "text",
      parentId: "category-community",
      topic: "Default community chat.",
    },
    {
      id: "game-chat",
      name: "game-chat",
      kind: "text",
      parentId: "category-community",
      topic: "Game-specific chat, queue talk, and party coordination.",
    },
    {
      id: "off-topic",
      name: "off-topic",
      kind: "text",
      parentId: "category-community",
      topic: "Casual community conversation that does not fit the main chat.",
    },
    { id: "category-voice", name: "VOICE", kind: "category" },
    {
      id: "voice-lobby",
      name: "Lobby",
      kind: "voice",
      parentId: "category-voice",
    },
    {
      id: "voice-gaming",
      name: "Gaming",
      kind: "voice",
      parentId: "category-voice",
      userLimit: 10,
    },
    {
      id: "voice-stream-waiting-room",
      name: "Stream Waiting Room",
      kind: "voice",
      parentId: "category-voice",
      userLimit: 8,
    },
    {
      id: "voice-afk",
      name: "AFK",
      kind: "voice",
      parentId: "category-voice",
    },
    { id: "category-staff", name: "STAFF", kind: "category" },
    {
      id: "staff-chat",
      name: "staff-chat",
      kind: "text",
      parentId: "category-staff",
      topic:
        "Private staff coordination for stream-day notes, moderation handoffs, event prep, and Console action review. Review Discord permissions after setup.",
    },
    {
      id: "mod-log",
      name: "mod-log",
      kind: "text",
      parentId: "category-staff",
      topic: "Moderation notes and VaexCore community operations logs.",
    },
  ],
  recommended: {
    streamAnnouncementChannelId: "live-now",
    generalAnnouncementChannelId: "announcements",
    suggestionChannelId: "suggestions",
    streamAlertsRoleId: "stream-alerts",
  },
};
